packages:
  - 'apps/*'
  - 'packages/*'

verifyDepsBeforeRun: error

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  core-js: false
  es5-ext: false
  esbuild: true
  prisma: true
  vue-demi: true

catalog:
  '@commitlint/cli': 21.0.2
  '@commitlint/config-conventional': 21.0.2
  '@element-plus/icons-vue': 2.3.2
  '@eslint/js': 10.0.1
  '@nestjs/common': 11.1.28
  '@nestjs/config': 4.0.4
  '@nestjs/core': 11.1.28
  '@nestjs/platform-fastify': 11.1.28
  '@prisma/adapter-pg': 7.9.0
  '@prisma/client': 7.9.0
  '@rsbuild/core': 2.1.5
  '@rsbuild/plugin-image-compress': 1.3.4
  '@rsbuild/plugin-sass': 2.0.1
  '@rsbuild/plugin-vue': 2.0.1
  '@rstest/core': 0.11.8
  '@types/node': 25.0.3
  '@vue/eslint-config-prettier': 10.2.0
  axios: 1.17.0
  class-transformer: 0.5.1
  class-validator: 0.15.1
  compression-webpack-plugin: 12.0.0
  cross-env: 10.1.0
  dotenv-cli: 11.0.0
  echarts: 6.1.0
  element-plus: 2.14.2
  eslint: 10.6.0
  eslint-plugin-vue: 10.9.2
  fastify: 5.6.2
  globals: 17.7.0
  happy-dom: 20.11.6
  husky: 9.1.7
  lint-staged: 17.0.8
  pg: 8.22.0
  pinia: 3.0.4
  prettier: 3.9.5
  prisma: 7.9.0
  reflect-metadata: 0.2.2
  rimraf: 6.1.3
  rxjs: 7.8.2
  sass: 1.101.0
  tsx: 4.23.0
  turbo: 2.10.4
  typescript: 6.0.2
  typescript-eslint: 8.63.0
  unplugin-auto-import: 21.0.0
  unplugin-vue-components: 32.1.0
  vue: 3.5.39
  vue-eslint-parser: 10.4.1
  vue-router: 5.2.0
  vue-tsc: 3.3.7

overrides:
  'ini@<1.3.6': 1.3.8
  vue: 'catalog:'
  typescript: 'catalog:'

minimumReleaseAgeExclude:
  - happy-dom@20.11.6
