/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseBadge: typeof import('./src/components/base/base-badge/index.vue')['default']
    BaseEmptyState: typeof import('./src/components/base/base-empty-state/index.vue')['default']
    CircleLoading: typeof import('./src/components/base/circle-loading/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
