import {
  Activity,
  AlarmClock,
  Archive,
  BadgeDollarSign,
  Bell,
  BookOpen,
  Boxes,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  ChartNoAxesColumnIncreasing,
  CheckCircle2,
  CircleHelp,
  CircleUserRound,
  ClipboardCheck,
  Cloud,
  CloudUpload,
  Cog,
  Contact,
  CreditCard,
  Database,
  FileArchive,
  FileChartColumn,
  FileCog,
  FileImage,
  FileSpreadsheet,
  FileText,
  Folder,
  FolderCog,
  Gauge,
  Globe2,
  HardDrive,
  House,
  IdCard,
  Image,
  KeyRound,
  Landmark,
  Languages,
  LayoutDashboard,
  Library,
  ListChecks,
  LockKeyhole,
  Mail,
  Map as MapIcon,
  Megaphone,
  Menu,
  MessageCircle,
  MonitorCog,
  Network,
  NotebookTabs,
  Package,
  PanelsTopLeft,
  PieChart,
  ReceiptText,
  Rocket,
  Search,
  ServerCog,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SquareChartGantt,
  Store,
  Tags,
  TimerReset,
  Truck,
  UserCog,
  UserRound,
  UsersRound,
  Video,
  WalletCards,
  Warehouse,
  Wrench,
} from '@lucide/vue';

import type { Component } from 'vue';
import type { MenuIconCategory, MenuIconOption } from '@/types';

/**
 * 菜单图标选择器的固定分类顺序
 */
export const MENU_ICON_CATEGORIES: readonly MenuIconCategory[] = [
  '常用',
  '用户组织',
  '权限安全',
  '数据系统',
  '文件内容',
  '业务管理',
  '财务统计',
  '消息通知',
  '时间任务',
  '状态工具',
];

/**
 * 后台管理场景的 Lucide 图标白名单
 *
 * 只显式导入一级菜单可能使用的图标，排除箭头、方向、编辑器排版等不适合作为导航语义的图标。
 * 注册表同时供菜单选择器、组件中心和数据库菜单渲染使用，避免维护多份名称映射。
 */
export const MENU_ICON_OPTIONS: readonly MenuIconOption[] = [
  { name: 'House', label: '首页', category: '常用', keywords: 'home 首页 主页', component: House },
  {
    name: 'LayoutDashboard',
    label: '工作台',
    category: '常用',
    keywords: 'dashboard 仪表盘 工作台',
    component: LayoutDashboard,
  },
  { name: 'Settings', label: '系统设置', category: '常用', keywords: 'settings 系统 设置', component: Settings },
  { name: 'Boxes', label: '组件模块', category: '常用', keywords: 'boxes 组件 模块', component: Boxes },
  {
    name: 'PanelsTopLeft',
    label: '页面面板',
    category: '常用',
    keywords: 'panels 页面 面板',
    component: PanelsTopLeft,
  },
  { name: 'Menu', label: '菜单', category: '常用', keywords: 'menu 菜单 导航', component: Menu },
  { name: 'Search', label: '搜索', category: '常用', keywords: 'search 搜索 查询', component: Search },
  { name: 'Gauge', label: '仪表盘', category: '常用', keywords: 'gauge 仪表 监控', component: Gauge },
  { name: 'UserRound', label: '用户', category: '用户组织', keywords: 'user 用户 账号', component: UserRound },
  {
    name: 'UsersRound',
    label: '用户组',
    category: '用户组织',
    keywords: 'users 用户组 团队',
    component: UsersRound,
  },
  { name: 'UserCog', label: '用户配置', category: '用户组织', keywords: '用户 配置 管理', component: UserCog },
  {
    name: 'CircleUserRound',
    label: '个人中心',
    category: '用户组织',
    keywords: 'profile 个人 头像',
    component: CircleUserRound,
  },
  { name: 'Contact', label: '联系人', category: '用户组织', keywords: 'contact 联系人 通讯录', component: Contact },
  { name: 'IdCard', label: '身份资料', category: '用户组织', keywords: 'id 身份 资料', component: IdCard },
  { name: 'Building2', label: '组织机构', category: '用户组织', keywords: 'building 组织 公司', component: Building2 },
  {
    name: 'BriefcaseBusiness',
    label: '岗位职务',
    category: '用户组织',
    keywords: 'business 岗位 职务',
    component: BriefcaseBusiness,
  },
  {
    name: 'ShieldCheck',
    label: '权限安全',
    category: '权限安全',
    keywords: 'shield 权限 安全',
    component: ShieldCheck,
  },
  { name: 'LockKeyhole', label: '访问控制', category: '权限安全', keywords: 'lock 锁 权限', component: LockKeyhole },
  { name: 'KeyRound', label: '密钥', category: '权限安全', keywords: 'key 密钥 密码', component: KeyRound },
  {
    name: 'ClipboardCheck',
    label: '审批审核',
    category: '权限安全',
    keywords: '审核 审批 检查',
    component: ClipboardCheck,
  },
  { name: 'Database', label: '数据库', category: '数据系统', keywords: 'database 数据库 数据', component: Database },
  { name: 'ServerCog', label: '服务配置', category: '数据系统', keywords: 'server 服务 配置', component: ServerCog },
  { name: 'MonitorCog', label: '系统监控', category: '数据系统', keywords: 'monitor 系统 监控', component: MonitorCog },
  { name: 'HardDrive', label: '存储服务', category: '数据系统', keywords: 'drive 存储 磁盘', component: HardDrive },
  { name: 'Cloud', label: '云服务', category: '数据系统', keywords: 'cloud 云 服务', component: Cloud },
  { name: 'Network', label: '网络服务', category: '数据系统', keywords: 'network 网络 节点', component: Network },
  { name: 'Activity', label: '运行状态', category: '数据系统', keywords: 'activity 状态 活跃', component: Activity },
  { name: 'FileText', label: '文档', category: '文件内容', keywords: 'file 文档 内容', component: FileText },
  { name: 'Folder', label: '文件夹', category: '文件内容', keywords: 'folder 文件夹 目录', component: Folder },
  { name: 'FolderCog', label: '文件配置', category: '文件内容', keywords: 'folder 文件 配置', component: FolderCog },
  { name: 'FileImage', label: '图片文件', category: '文件内容', keywords: 'image 图片 文件', component: FileImage },
  {
    name: 'FileSpreadsheet',
    label: '电子表格',
    category: '文件内容',
    keywords: 'excel 表格 文件',
    component: FileSpreadsheet,
  },
  {
    name: 'FileArchive',
    label: '文件归档',
    category: '文件内容',
    keywords: 'archive 归档 压缩',
    component: FileArchive,
  },
  {
    name: 'FileChartColumn',
    label: '数据报表',
    category: '文件内容',
    keywords: 'report 报表 数据',
    component: FileChartColumn,
  },
  { name: 'FileCog', label: '文件设置', category: '文件内容', keywords: 'file 文件 设置', component: FileCog },
  { name: 'Image', label: '图片中心', category: '文件内容', keywords: 'image 图片 素材', component: Image },
  { name: 'Video', label: '视频中心', category: '文件内容', keywords: 'video 视频 媒体', component: Video },
  { name: 'BookOpen', label: '知识内容', category: '文件内容', keywords: 'book 知识 内容', component: BookOpen },
  { name: 'Library', label: '内容库', category: '文件内容', keywords: 'library 内容 库', component: Library },
  {
    name: 'NotebookTabs',
    label: '栏目管理',
    category: '文件内容',
    keywords: 'tabs 栏目 标签',
    component: NotebookTabs,
  },
  { name: 'Package', label: '产品', category: '业务管理', keywords: 'package 产品 包裹', component: Package },
  { name: 'ShoppingBag', label: '商品', category: '业务管理', keywords: 'shopping 商品 购物', component: ShoppingBag },
  {
    name: 'ShoppingCart',
    label: '购物车',
    category: '业务管理',
    keywords: 'cart 购物车 订单',
    component: ShoppingCart,
  },
  { name: 'Store', label: '店铺', category: '业务管理', keywords: 'store 店铺 门店', component: Store },
  { name: 'Warehouse', label: '仓库', category: '业务管理', keywords: 'warehouse 仓库 库存', component: Warehouse },
  { name: 'Truck', label: '物流', category: '业务管理', keywords: 'truck 物流 配送', component: Truck },
  { name: 'Tags', label: '标签分类', category: '业务管理', keywords: 'tags 标签 分类', component: Tags },
  { name: 'Map', label: '区域地图', category: '业务管理', keywords: 'map 地图 区域', component: MapIcon },
  { name: 'Globe2', label: '全球业务', category: '业务管理', keywords: 'globe 全球 国际', component: Globe2 },
  {
    name: 'Languages',
    label: '多语言',
    category: '业务管理',
    keywords: 'language 多语言 国际化',
    component: Languages,
  },
  { name: 'WalletCards', label: '钱包', category: '财务统计', keywords: 'wallet 钱包 财务', component: WalletCards },
  { name: 'CreditCard', label: '支付', category: '财务统计', keywords: 'card 支付 银行卡', component: CreditCard },
  {
    name: 'BadgeDollarSign',
    label: '金额',
    category: '财务统计',
    keywords: 'money 金额 收益',
    component: BadgeDollarSign,
  },
  { name: 'Landmark', label: '财务机构', category: '财务统计', keywords: 'bank 银行 财务', component: Landmark },
  { name: 'ReceiptText', label: '账单', category: '财务统计', keywords: 'receipt 账单 发票', component: ReceiptText },
  { name: 'PieChart', label: '占比统计', category: '财务统计', keywords: 'pie chart 饼图 统计', component: PieChart },
  {
    name: 'ChartNoAxesColumnIncreasing',
    label: '增长趋势',
    category: '财务统计',
    keywords: 'chart 趋势 增长',
    component: ChartNoAxesColumnIncreasing,
  },
  {
    name: 'SquareChartGantt',
    label: '项目计划',
    category: '财务统计',
    keywords: 'gantt 项目 计划',
    component: SquareChartGantt,
  },
  { name: 'Bell', label: '通知', category: '消息通知', keywords: 'bell 通知 提醒', component: Bell },
  { name: 'Mail', label: '邮件', category: '消息通知', keywords: 'mail 邮件 信箱', component: Mail },
  {
    name: 'MessageCircle',
    label: '消息',
    category: '消息通知',
    keywords: 'message 消息 会话',
    component: MessageCircle,
  },
  { name: 'Megaphone', label: '公告', category: '消息通知', keywords: 'megaphone 公告 广播', component: Megaphone },
  {
    name: 'CalendarDays',
    label: '日历',
    category: '时间任务',
    keywords: 'calendar 日历 日期',
    component: CalendarDays,
  },
  { name: 'AlarmClock', label: '提醒', category: '时间任务', keywords: 'alarm 提醒 闹钟', component: AlarmClock },
  { name: 'TimerReset', label: '定时任务', category: '时间任务', keywords: 'timer 定时 任务', component: TimerReset },
  { name: 'ListChecks', label: '任务清单', category: '时间任务', keywords: 'todo 任务 清单', component: ListChecks },
  {
    name: 'CheckCircle2',
    label: '成功状态',
    category: '状态工具',
    keywords: 'check 成功 完成',
    component: CheckCircle2,
  },
  { name: 'CircleHelp', label: '帮助中心', category: '状态工具', keywords: 'help 帮助 问题', component: CircleHelp },
  { name: 'Cog', label: '配置', category: '状态工具', keywords: 'cog 配置 设置', component: Cog },
  { name: 'Wrench', label: '工具', category: '状态工具', keywords: 'wrench 工具 维护', component: Wrench },
  {
    name: 'CloudUpload',
    label: '云端上传',
    category: '状态工具',
    keywords: 'upload 上传 云端',
    component: CloudUpload,
  },
  { name: 'Archive', label: '归档', category: '状态工具', keywords: 'archive 归档 收纳', component: Archive },
  { name: 'Rocket', label: '发布部署', category: '状态工具', keywords: 'rocket 发布 部署', component: Rocket },
];

/**
 * 菜单图标名称到 Vue 组件的解析表
 */
const MENU_ICON_COMPONENTS = new Map<string, Component>(
  MENU_ICON_OPTIONS.map((option) => [option.name, option.component]),
);

/**
 * 解析数据库菜单保存的 Lucide 图标名称
 *
 * @param name 菜单表中的图标名称
 * @returns 白名单中的 Vue 图标组件；名称为空或已移除时返回 `undefined`
 */
export const resolveMenuIcon = (name: string | null | undefined): Component | undefined => {
  return name ? MENU_ICON_COMPONENTS.get(name) : undefined;
};
